[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "directory-service"
version = "0.0.1"
dependencies = [
    'ldap',
    'yaml',
    'python_version<"3.8"',
]
